using System;

namespace ARDrone2Client.Common.Configuration.Native
{
    public enum ARDRONE_LED_ANIMATION
    {
        ARDRONE_LED_ANIMATION_BLINK_GREEN_RED,
        ARDRONE_LED_ANIMATION_BLINK_GREEN,
        ARDRONE_LED_ANIMATION_BLINK_RED,
        ARDRONE_LED_ANIMATION_BLINK_ORANGE,
        ARDRONE_LED_ANIMATION_SNAKE_GREEN_RED,
        ARDRONE_LED_ANIMATION_FIRE,
        ARDRONE_LED_ANIMATION_STANDARD,
        ARDRONE_LED_ANIMATION_RED,
        ARDRONE_LED_ANIMATION_GREEN,
        ARDRONE_LED_ANIMATION_RED_SNAKE,
        ARDRONE_LED_ANIMATION_BLANK,
        ARDRONE_LED_ANIMATION_RIGHT_MISSILE,
        ARDRONE_LED_ANIMATION_LEFT_MISSILE,
        ARDRONE_LED_ANIMATION_DOUBLE_MISSILE,
        ARDRONE_LED_ANIMATION_FRONT_LEFT_GREEN_OTHERS_RED,
        ARDRONE_LED_ANIMATION_FRONT_RIGHT_GREEN_OTHERS_RED,
        ARDRONE_LED_ANIMATION_REAR_RIGHT_GREEN_OTHERS_RED,
        ARDRONE_LED_ANIMATION_REAR_LEFT_GREEN_OTHERS_RED,
        ARDRONE_LED_ANIMATION_LEFT_GREEN_RIGHT_RED,
        ARDRONE_LED_ANIMATION_LEFT_RED_RIGHT_GREEN,
        ARDRONE_LED_ANIMATION_BLINK_STANDARD
    }
}