using System;

namespace ARDrone2Client.Common.Configuration.Native
{
    public enum ARDRONE_VIDEO_CHANNEL
    {
        ARDRONE_VIDEO_CHANNEL_FIRST = 0,
        ARDRONE_VIDEO_CHANNEL_HORI = ARDRONE_VIDEO_CHANNEL_FIRST,
        ARDRONE_VIDEO_CHANNEL_VERT,
        ARDRONE_VIDEO_CHANNEL_LARGE_HORI_SMALL_VERT,
        ARDRONE_VIDEO_CHANNEL_LARGE_VERT_SMALL_HORI,
        ARDRONE_VIDEO_CHANNEL_LAST = ARDRONE_VIDEO_CHANNEL_LARGE_VERT_SMALL_HORI,
        ARDRONE_VIDEO_CHANNEL_NEXT
    }
}