using System;

namespace ARDrone2Client.Common.Configuration.Native
{
    public enum ARDRONE_ANIMATION
    {
        ARDRONE_ANIMATION_PHI_M30_DEG = 0,
        ARDRONE_ANIMATION_PHI_30_DEG,
        ARDRONE_ANIMATION_THETA_M30_DEG,
        ARDRONE_ANIMATION_THETA_30_DEG,
        ARDRONE_ANIMATION_THETA_20DEG_YAW_200DEG,
        ARDRONE_ANIMATION_THETA_20DEG_YAW_M200DEG,
        ARDRONE_ANIMATION_TURNAROUND,
        ARDRONE_ANIMATION_TURNAROUND_GODOWN,
        ARDRONE_ANIMATION_YAW_SHAKE,
        ARDRONE_ANIMATION_YAW_DANCE,
        ARDRONE_ANIMATION_PHI_DANCE,
        ARDRONE_ANIMATION_THETA_DANCE,
        ARDRONE_ANIMATION_VZ_DANCE,
        ARDRONE_ANIMATION_WAVE,
        ARDRONE_ANIMATION_PHI_THETA_MIXED,
        ARDRONE_ANIMATION_DOUBLE_PHI_THETA_MIXED,
        ARDRONE_ANIMATION_FLIP_AHEAD,
        ARDRONE_ANIMATION_FLIP_BEHIND,
        ARDRONE_ANIMATION_FLIP_LEFT,
        ARDRONE_ANIMATION_FLIP_RIGHT
    }
}