using System;

namespace ARDrone2Client.Common.Configuration.Native
{
    public enum ARDRONE_CAMERA_DETECTION_TYPE
    {
        ARDRONE_CAMERA_DETECTION_HORIZONTAL = 0,
        ARDRONE_CAMERA_DETECTION_VERTICAL,
        ARDRONE_CAMERA_DETECTION_VISION,
        ARDRONE_CAMERA_DETECTION_NONE,
        ARDRONE_CAMERA_DETECTION_COCARDE,
        ARDRONE_CAMERA_DETECTION_ORIENTED_COCARDE,
        ARDRONE_CAMERA_DETECTION_STRIPE,
        ARDRONE_CAMERA_DETECTION_H_COCARDE,
        ARDRONE_CAMERA_DETECTION_H_ORIENTED_COCARDE,
        ARDRONE_CAMERA_DETECTION_STRIPE_V,
        ARDRONE_CAMERA_DETECTION_MULTIPLE_DETECTION_MODE,
        ARDRONE_CAMERA_DETECTION_CAP,
        ARDRONE_CAMERA_DETECTION_ORIENTED_COCARDE_BW,
        ARDRONE_CAMERA_DETECTION_VISION_V2,
        ARDRONE_CAMERA_DETECTION_TOWER_SIDE,
        ARDRONE_CAMERA_DETECTION_NUM
    }
}