#ifndef _VIDEO_ENCAPSULATION_FRAME_TYPE_
#define _VIDEO_ENCAPSULATION_FRAME_TYPE_

enum video_encapsulation_frametypes_t
{
    FRAME_TYPE_UNKNNOWN,
    FRAME_TYPE_IDR_FRAME,
    FRAME_TYPE_I_FRAME,
    FRAME_TYPE_P_FRAME,
    FRAME_TYPE_HEADERS,
};

#endif